cluster:
  cloud: amazon
  location: eu-west-2
  name: h2ick6o929xck
  properties:
    eks:
      nodePools:
        pool1:
          autoscaling: true
          count: 1
          instanceType: t2.medium
          maxCount: 2
          minCount: 1
          spotPrice: "0.052"
        pool2:
          autoscaling: true
          count: 1
          instanceType: c5.large
          maxCount: 2
          minCount: 1
          spotPrice: "0.101"
        pool3:
          autoscaling: true
          count: 1
          instanceType: t2.large
          maxCount: 2
          minCount: 1
          spotPrice: "0.1056"
      version: 1.14.7
  secretName: sancyx-aws
pipeline:
  install_kubeflow_auth_secrets:
    action: InstallSecret
    clusterSecret:
      merge: true
      name: '{{ .CICD_REPO_NAME }}-kubeflow-auth'
      namespace: kubeflow
      sourceSecretName: kubeflowpass
      spec: []
    image: banzaicloud/ci-pipeline-client:0.12
  get_cluster_config:
    client:
      kubeconfig: /drone/kubeconfig.yaml
    image: banzaicloud/ci-pipeline-client:dev
    action: GetCluster
  install_kubeflow:
    image: banzaicloud/deploy-kubeflow:dev
    commands:
    - KUBECONFIG=''/drone/kubeconfig.yaml'
    - backyards istio install -f /opt/kubeflow/mesh.yaml
    - cd /opt/kubeflow/app
    - KUBEFLOW_PASSWORD=$(KUBECONFIG=/drone/kubeconfig.yaml kubectl get secret '{{ .CICD_REPO_NAME }}-kubeflow-auth' -n kubeflow -o yaml | yq r - data.password | base64 -d)
    - KUBEFLOW_USER_EMAIL=$(KUBECONFIG=/drone/kubeconfig.yaml kubectl get secret '{{ .CICD_REPO_NAME }}-kubeflow-auth' -n kubeflow -o yaml | yq r - data.username | base64 -d)
    - INSTALL_ISTIO="false" kfctl apply all -V
  package_application:
    image: lachlanevenson/k8s-helm:v2.16.1
    commands:
    - helm init -c
    - helm package ./.banzaicloud/charts/spotguide-kubeflow
  deploy_application:
    action: EnsureDeployment
    deployment:
      name: ./spotguide-kubeflow-1.0.0.tgz
      namespace: kubeflow
      releaseName: '{{ .CICD_REPO_NAME }}'
      values:
        banzaicloud:
          secret:
            zeppelin: kubeflowpass
        enterprise-gateway:
          image: banzaicloud/enterprise-gateway:dev
          ingress.enabled: false
    image: banzaicloud/ci-pipeline-client:0.12
